[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ff1=true

optimizer = true
optimizer_runs = 200
via_ir = true
remappings = ["forge-std/=lib/forge-std/src/", "@chainlink/contracts/src/v0.8/vrf/=lib/chainlink-brownie-contracts/contracts/src/v0.8/", "@chainlink/contracts/src/v0.8/automation/v2_1=lib/chainlink-brownie-contracts/contracts/src/v0.8/automation/v2_1", "@solmate=lib/solmate/src"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
