[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts@1.2.0/=lib/chainlink-brownie-contracts/contracts/",  "@solmate=lib/solmate/src"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# "forge-std/=lib/forge-std/src/",